In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [2]:
#read csv file
df=pd.read_csv('iris_flowers.csv')
df.head()#first 5 rows

sepal_length  sepal_width  petal_length   petal_width        class
0           5.1          3.5           1.4           0.2  iris_setosa
1           4.9          3.0           1.4           0.2  iris_setosa
2           4.7          3.2           1.3           0.2  iris_setosa
3           4.6          3.1           1.5           0.2  iris_setosa
4           5.0          3.6           1.4           0.2  iris_setosa

In [3]:
#display column names of the csv file
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', ' petal_width', 'class'], dtype='object')

In [4]:
#convert the categorical class value to integer
number=LabelEncoder()
df['class']=number.fit_transform(df['class'].astype(str))
df.head()

sepal_length  sepal_width  petal_length   petal_width  class
0           5.1          3.5           1.4           0.2      0
1           4.9          3.0           1.4           0.2      0
2           4.7          3.2           1.3           0.2      0
3           4.6          3.1           1.5           0.2      0
4           5.0          3.6           1.4           0.2      0

In [5]:
#save predictor values to array X
X=df[['sepal_length','sepal_width','petal_length',' petal_width']].values
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
#save class values to array y
y=df['class'].values
y[0:5]

array([0, 0, 0, 0, 0])

In [7]:
#split the dataset into train and test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)
print("Train:",X_train.shape,y_train.shape)
print("Test:",X_test.shape,y_test.shape)

Train: (120, 4) (120,)
Test: (30, 4) (30,)


In [8]:
#train
k=5
neigh=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
neigh
#predict
x=[[]]
y_=neigh.predict(X_test)
y_

array([1, 2, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 2, 1, 2, 1, 1, 1, 2])

In [9]:
#accuracy
print("Training Set Accuracy:",metrics.accuracy_score(y_train,neigh.predict(X_train)))
print("Testing Set Accuracy",metrics.accuracy_score(y_test,y_))

Training Set Accuracy: 0.9833333333333333
Testing Set Accuracy 0.9333333333333333


In [10]:
#confusion matrix
print(metrics.confusion_matrix(y_test,y_))
print(metrics.classification_report(y_test,y_,digits=3))

[[ 8  0  0]
 [ 0  9  2]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0      1.000     1.000     1.000         8
           1      1.000     0.818     0.900        11
           2      0.846     1.000     0.917        11

    accuracy                          0.933        30
   macro avg      0.949     0.939     0.939        30
weighted avg      0.944     0.933     0.933        30

